Issue/7752
easydigitaldownloads/easy-digital-downloads pull request #7765
Opened 2020-04-20 19:29 UTC by robincornett

Fixes #7752

Proposed Changes:
Adds visually hidden labels to checkbox inputs in EDD custom tables, which include:
- Orders
- Customers
- Customer email addresses
- Customer physical addresses
- Discount codes
- Order adjustments
- Order items
- Refund items (modal)

2020-04-21 13:25 UTC, ashleyfae commented on includes/admin/payments/class-order-adjustments-table.php
> +		$name = '&mdash;';
Because `$name` is only used at the end, you could remove this variable and just put this at the very end:

```php
return '&mdash;';
```

2020-09-11 13:43 UTC, ashleyfae requested changes

2020-09-11 13:43 UTC, ashleyfae commented on includes/admin/customers/class-customer-addresses-table.php
> +			sprintf( __( 'Select %s', 'easy-digital-downloads' ), $name )
```suggestion
			esc_html( sprintf( __( 'Select %s', 'easy-digital-downloads' ), $name ) )
```

2020-09-11 13:43 UTC, ashleyfae commented on includes/admin/customers/class-customer-email-addresses-table.php
> +			sprintf( __( 'Select %s', 'easy-digital-downloads' ), $item['email'] ),
```suggestion
			esc_html( sprintf( __( 'Select %s', 'easy-digital-downloads' ), $item['email'] ) ),
```

2020-09-11 13:43 UTC, ashleyfae commented on includes/admin/discounts/class-discount-codes-table.php
> +			sprintf( __( 'Select %s', 'easy-digital-downloads' ), $discount->name )
```suggestion
			esc_html( sprintf( __( 'Select %s', 'easy-digital-downloads' ), $discount->name ) )
```

2020-09-11 13:43 UTC, ashleyfae commented on includes/admin/discounts/class-discount-codes-table.php
> +			/*$2%s*/ $discount->id,
```suggestion
			/*$2%s*/ esc_attr( $discount->id ),
```

2020-09-11 13:43 UTC, ashleyfae commented on includes/admin/customers/class-customer-addresses-table.php
> +			/*$2%s*/ $item['id'],
```suggestion
			/*$2%s*/ esc_attr( $item['id'] ),
```

2020-09-11 13:43 UTC, ashleyfae commented on includes/admin/payments/class-payments-table.php
> +			$order->id,
```suggestion
			esc_attr( $order->id ),
```

2020-09-11 13:43 UTC, ashleyfae commented on includes/admin/payments/class-payments-table.php
> +			sprintf( __( 'Select %s', 'easy-digital-downloads' ), $order_number )
```suggestion
			esc_html( sprintf( __( 'Select %s', 'easy-digital-downloads' ), $order_number ) )
```

2020-09-11 13:43 UTC, ashleyfae commented on includes/admin/payments/class-refund-items-table.php
> +				$order_item->id,
```suggestion
				esc_attr( $order_item->id ),
```

2020-09-11 13:43 UTC, ashleyfae commented on includes/admin/payments/class-refund-items-table.php
> +				sprintf( __( 'Select %s', 'easy-digital-downloads' ), $order_item->product_name )
```suggestion
				esc_html( sprintf( __( 'Select %s', 'easy-digital-downloads' ), $order_item->product_name ) )
```

2020-09-11 13:43 UTC, ashleyfae commented on includes/admin/customers/class-customer-table.php
> +			/*$2%s*/ $item['id'],
```suggestion
			/*$2%s*/ esc_attr( $item['id'] ),
```

2020-09-11 13:43 UTC, ashleyfae commented on includes/admin/customers/class-customer-table.php
> +			sprintf( __( 'Select %s', 'easy-digital-downloads' ), $name )
```suggestion
			esc_html( sprintf( __( 'Select %s', 'easy-digital-downloads' ), $name ) )
```

2020-09-11 16:21 UTC, spencerfinnell approved these changes

2020-09-13 23:24 UTC, LisaCee approved these changes

2020-09-14 11:35 UTC, ashleyfae approved these changes

2020-09-14 11:35 UTC, merged