X Buttons Visible on All Screens
easydigitaldownloads/easy-digital-downloads pull request #8158
Opened 2020-10-22 17:38 UTC by LisaCee

Fixes #8157 

Proposed Changes:
1. Add media query to offset buttons only on larger screens
2. Tweak media query to match when table responds

I'm not crazy about this solution, but it works. I'm still digging for the code that makes the table expand to see if I can tweak that rather than the media query.  I'd love to see the table respond at 782px, a more standard tablet breakpoint.

2020-10-23 18:10 UTC, spencerfinnell requested changes
I like this much simpler solution @LisaCee.

2020-10-23 18:10 UTC, spencerfinnell commented on assets/css/edd-admin.css
> +		margin-left: -40px;
@LisaCee Let's do `-50px` so the text lines up with the other items below it.

2020-10-23 18:32 UTC, robincornett approved these changes
This looks good to me. I can't test it with the adjustments row because I updated my local to the 5.6 beta and adjustments are not working, but assume someone else can check adjustments?

2020-10-23 18:43 UTC, spencerfinnell approved these changes

2020-10-28 11:15 UTC, ashleyfae approved these changes

2020-10-28 11:16 UTC, merged