Update customer stats via ajax when recalculating single customer
easydigitaldownloads/easy-digital-downloads pull request #8201
Opened 2020-11-11 20:33 UTC by robincornett

Fixes #8004

Proposed Changes:
1. Adds a new class `$data` variable to `EDD_Tools_Recount_Single_Customer_Stats`.
2. On success, the new purchase count and value are sent to the JavaScript.
3. The `span` which match the data keys are updated with the new values.

My thought on how the script is updating the matching `span` is that this is something that other export classes could use if needed--the array of data returned would just have to set the keys to match an element with a matching class (prepended with `edd_`). In that case, it might be better to define the new `$data` variable in `EDD_Batch_Export`, but this is a start.

To test:
1. Visit the Customer Details screen for any customer.
2. Use your browser's dev tools to change the numbers for the "Completed Sales" and "Lifetime Value". (You could also do this directly in the database, but this felt easier.)
3. Go to Tools for the customer.
4. Click the Recount Stats button.
5. When the success message appears, click on the customer Profile link.
6. The stats should be updated to the new/correct values.

2020-11-12 20:04 UTC, spencerfinnell requested changes

2020-11-12 20:04 UTC, spencerfinnell commented on includes/admin/customers/customers.php
> +					<?php printf( _n( '<span class="edd_purchase_count">%s</span> Completed Sale', '<span class="edd_purchase_count">%s</span> Completed Sales', $customer->purchase_count, 'easy-digital-downloads' )
The HTML should wrap around the placeholder so translators do not accidentally remove it.

```suggestion
					<?php
					printf(
						_n(
							'%s Completed Sale',
							'%s Completed Sales',
							$customer->purchase_count,
							'easy-digital-downloads'
						),
						(
							'<span class="edd_purchase_count">' .
							esc_html( number_format_i18n( $customer->purchase_count, 0 ) ) .
							'</span>'
						)
					);
					?>
```

2020-11-12 20:04 UTC, spencerfinnell commented on includes/admin/customers/customers.php
> +				<?php echo '<span class="edd_purchase_value">' . esc_html( edd_currency_filter( edd_format_amount( $customer->purchase_value ) ) ) . '</span>'; ?> <?php esc_html_e( 'Lifetime Value', 'easy-digita
Would be nice to update this similarly to the "Completed Sale" string for better translatability.

2020-11-12 20:04 UTC, spencerfinnell commented on assets/js/admin/tools/export/index.js
> +								$( '.edd_' + key ).empty().append( value );
```suggestion
								$( '.edd_' + key ).html( value );
```

`.html()` will replace any of the existing content.

2020-11-12 20:44 UTC, spencerfinnell requested changes

2020-11-12 20:44 UTC, spencerfinnell commented on includes/admin/customers/customers.php
> +							/* translators: the customer's lifetime number of sales */
```suggestion
						/* translators: the customer's lifetime number of sales */
						_n(
```

2020-11-12 20:48 UTC, spencerfinnell approved these changes

2020-11-13 13:23 UTC, ashleyfae approved these changes

2020-11-13 13:23 UTC, merged