Fix user fallback if user is not in initial batch for user_dropdown
easydigitaldownloads/easy-digital-downloads pull request #8226
Opened 2020-11-27 19:22 UTC by robincornett

Fixes #8224

Proposed Changes:
1. Updates the user dropdown function to accept an array of selected users when making sure that a selected user will appear in the initial batch.

To test:
1. Check out the [1.5-master-merge branch](https://github.com/easydigitaldownloads/edd-discounts-pro/tree/release/1.5-master-merge) for Discounts Pro (the issue is not present in `master`).
2. With `release/2.10`, create a discount for a specific user and see the error indicated in the related issue.
3. Switch to this branch and the error should be resolved.

Notes: I referred to the `product_dropdown` method to set up the logic for this, as it also can be set to single/multiple.

2020-11-30 13:11 UTC, ashleyfae requested changes

2020-11-30 13:11 UTC, ashleyfae commented on includes/class-edd-html-elements.php
> +						$options[ absint( $args['selected'] ) ] = esc_html( $user->display_name );
```suggestion
						$options[ absint( $user->ID ) ] = esc_html( $user->display_name );
```

2020-11-30 13:24 UTC, ashleyfae approved these changes

2020-12-02 00:36 UTC, LisaCee approved these changes
Thanks for the instructions on how to replicate the error.

2020-12-02 09:13 UTC, merged