Define default/fresh admin color scheme
easydigitaldownloads/easy-digital-downloads pull request #8231
Opened 2020-11-30 19:23 UTC by robincornett

Fixes #8229

To test:
1. Visit a screen such as Exports.
2. Make sure that any select inputs using Chosen highlight a selection properly using the default (fresh) admin color scheme.
3. Make sure that the color is still correct when using an alternative color scheme.

2020-11-30 22:23 UTC, LisaCee requested changes
This works well, but the contrast between the default scheme and white font is really low on the Chosen dropdowns.  I feel there's probably a greater WP theme rule in play, but could we change the color to something darker like `#0073aa`?

2020-12-01 12:34 UTC, ashleyfae commented
I agree with @LisaCee . Also, what GitHub has done with that hex value is super cute.

2020-12-01 13:31 UTC, robincornett commented
Sorry, I had pulled a blue hover on black--will update to the default background color for the primary buttons, which is `#007cba`...not quite as dark as your suggestion, but closer.

2020-12-01 13:43 UTC, ashleyfae approved these changes

2020-12-01 17:35 UTC, LisaCee approved these changes

2020-12-02 13:22 UTC, merged