Update how discounts are displayed in the cart
easydigitaldownloads/easy-digital-downloads pull request #8239
Opened 2020-12-03 19:26 UTC by robincornett

Fixes #8236

Proposed Changes: initially I was just going to fix the output to show the proper discount rate, but after reading through the code with changes from #7993, it seemed important to figure out how to show the calculated discount amount, as that appeared to be the goal of the updated code (2.9.x shows just the discount rate, not the calculated/applied amount):

1. Show the calculated discount amount after the discount code. This has been updated to honor the storefront currency placement settings.
2. Additionally, for percentage discounts, the percentage is also displayed.
3. Prefixed the row with "Discount(s):" to be consistent with Subtotal, Tax, and Total rows.
4. Added link text to the `edd_discount_remove` link (hidden with `screen-reader-text`) for accessibility.

To test:
- Create multiple discounts: one flat rate, one percentage rate.
- Add items to the cart and apply one or both discounts (you may have to enable multiple discounts in settings). The prefix should properly show Discount(s) as singular or plural.
- Check the discounts with the currency position set to "after".

This adjusts the display only of the discounts--the calculations were already handled by Spencer in the other issue.

2020-12-04 21:09 UTC, LisaCee approved these changes
Tested with flat-rate, percentage, and currency with the symbol after the amount.

2020-12-08 14:50 UTC, ashleyfae requested changes

2020-12-08 14:50 UTC, ashleyfae commented on includes/discount-functions.php
> +			$remove_url,
```suggestion
			esc_url( $remove_url ),
```

2020-12-08 14:50 UTC, ashleyfae commented on includes/discount-functions.php
> +			$discount,
```suggestion
			esc_attr( $discount ),
```

2020-12-08 14:50 UTC, ashleyfae commented on includes/discount-functions.php
> +			__( 'Remove discount', 'easy-digital-downloads' )
```suggestion
			esc_attr__( 'Remove discount', 'easy-digital-downloads' )
```

2020-12-09 10:57 UTC, ashleyfae commented
Tested:

- [ ] Flat rate only
    - [ ] Currency position before
    - [ ] Currency position after
- [ ] Percentage only
    - [ ] Currency position before
    - [ ] Currency position after
- [ ] Flat rate and percentage
    - [ ] Currency position before
    - [ ] Currency position after

2020-12-09 11:02 UTC, ashleyfae approved these changes

2020-12-09 11:02 UTC, merged