Change selector of upload field on admin download page to take precedence over WordPress CSS
easydigitaldownloads/easy-digital-downloads pull request #8245
Opened 2020-12-04 18:50 UTC by napoleaowingert

# Fixes

1. I think the CSS selector in EDD needs to be changed like this:
from: .edd_upload_field
to: input[type="text"].edd_upload_field

Then it will work just fine as it takes precedence over WordPress CSS.

2021-01-25 14:29 UTC, ashleyfae requested changes
Thank you @napoleaowingert! I requested a minor change if you don't mind. :smiley:

2021-01-25 14:29 UTC, ashleyfae commented on assets/css/edd-admin.css
>  	padding-right: 8em;
I actually think I'd prefer an `!important` here and reverting the selector back to `.edd_upload_field` . That way we won't get caught out if we ever change the input type for whatever reason (not that I'm planning to, but you never know :shrug: ).

2021-04-08 16:39 UTC, napoleaowingert commented
Hi @ashleyfae, thank you for checking this! The requested change has already been made.

2021-04-14 08:20 UTC, ashleyfae approved these changes
Thank you! :raised_hands:

2021-04-14 08:20 UTC, merged