#8301 PHP version requirement
easydigitaldownloads/easy-digital-downloads pull request #8302
Opened 2021-01-12 22:26 UTC by LisaCee

Fixes #8301 

Proposed Changes:
1. Add PHP version requirement

2021-01-13 13:35 UTC, robincornett approved these changes

2021-01-18 10:31 UTC, ashleyfae commented
@LisaCee Can you also add the same 5.6 requirement here: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/97b73a3fc400d00045f8b7282c28d16ceb93818b/easy-digital-downloads.php#L67

and here: https://github.com/easydigitaldownloads/easy-digital-downloads/blob/97b73a3fc400d00045f8b7282c28d16ceb93818b/composer.json#L12

2021-01-21 19:00 UTC, robincornett requested changes
Sorry, it also needs to be updated in the [readme.txt file](https://github.com/easydigitaldownloads/easy-digital-downloads/blob/release/3.0/readme.txt#L9) too please! (In hindsight I think I erred when creating the issue--I think this is supposed to be in the readme file as opposed to the plugin header, but I'm okay with having it both places personally).

2021-01-22 13:28 UTC, robincornett approved these changes

2021-01-25 12:52 UTC, ashleyfae approved these changes

2021-01-25 12:52 UTC, merged