#8401 Check for missing data before adding tax rate
easydigitaldownloads/easy-digital-downloads pull request #8419
Opened 2021-02-19 18:15 UTC by LisaCee

Fixes #8401

Proposed Changes:
1. Check for selected country and show alert if missing
2.
3.

2021-02-22 11:00 UTC, ashleyfae requested changes
Brilliant job @LisaCee ! :raised_hands: Just a couple minor changes.

2021-02-22 11:00 UTC, ashleyfae commented on assets/js/admin/settings/tax-rates/views/table-add.js
> +		if ( this.model.get('amount') <= 0 ) {
```suggestion
		if ( this.model.get( 'amount' ) <= 0 ) {
```

Just some space around the parameter. :)

2021-02-22 18:49 UTC, robincornett approved these changes

2021-02-23 13:43 UTC, ashleyfae approved these changes

2021-02-23 13:43 UTC, merged