Add support for old get_x() methods #8655
easydigitaldownloads/easy-digital-downloads pull request #8656
Opened 2021-05-26 09:22 UTC by ashleyfae

Fixes #8655 

Proposed Changes:
1. Strip `get_` on incoming method calls.
2. If a method doesn't exist but a property does, call the method. I updated the existing call for this logic. Previously it was passing `$args` to the property, which... doesn't work. It was treating the property like a method instead of a property. My fix actually treats it like a property.

To test:

See original issue. Test both `get_ID()` and `get_name()` methods.

2021-05-26 16:44 UTC, LisaCee requested changes
The `get_name` function works for me, but I'm getting `NULL` for the `get_ID` function call.

This is the code I'm using for testing (thanks Debug console). It works for `get_name`.
$discount = edd_get_discount(1);
var_dump( $discount->get_ID());

2021-05-27 07:44 UTC, ashleyfae commented
Huh that's really weird. It's working for me. Sorry if this is a silly question, but do you definitely have a discount with the ID `1` ?

2021-05-27 16:46 UTC, LisaCee commented
> Huh that's really weird. It's working for me. Sorry if this is a silly question, but do you definitely have a discount with the ID `1` ?

Not a silly question, but yes. I tried it with a different discount in 3.0 and dumped everything.
```<?php
$discount = edd_get_discount(524);

var_dump($discount);
var_dump($discount->get_name());
var_dump($discount->get_ID());
```

resulted in
```
object(EDD_Discount)#2194 (21) { ["id":protected]=> int(524) ["name":protected]=> string(6) "10poff" ["code":protected]=> string(6) "10poff" ["status":protected]=> string(6) "active" ["amount_type":protected]=> string(7) "percent" ["amount":protected]=> string(12) "10.000000000" ["product_reqs":protected]=> array(0) { } ["scope":protected]=> string(6) "global" ["excluded_products":protected]=> array(0) { } ["product_condition":protected]=> string(3) "all" ["date_created":protected]=> string(19) "2021-05-04 18:09:29" ["date_modified":protected]=> string(19) "2021-05-04 19:47:01" ["start_date":protected]=> bool(false) ["end_date":protected]=> bool(false) ["use_count":protected]=> string(1) "2" ["max_uses":protected]=> string(1) "0" ["min_charge_amount":protected]=> string(11) "0.000000000" ["once_per_customer":protected]=> string(1) "0" ["db_global":protected]=> string(4) "wpdb" ["prefix":protected]=> string(3) "edd" ["last_error":protected]=> bool(false) } 

string(6) "10poff" 
NULL
```

2021-05-28 15:52 UTC, LisaCee approved these changes

2021-06-02 15:33 UTC, robincornett approved these changes
Tested:
- [x] 2.10
- [x] 3.0

2021-06-03 13:19 UTC, merged